# Generated by Django 5.0.3 on 2024-11-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_ingredient_tag_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='عکس کاور برای نمایش در لیست دستورها', null=True, upload_to='recipe_covers/%Y/%m/', verbose_name='عکس کاور'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='عکس اصلی دستور پخت', null=True, upload_to='recipe_images/%Y/%m/', verbose_name='عکس دستور پخت'),
        ),
    ]
