# Generated by Django 4.2.7 on 2024-11-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipe_ingredients',
            field=models.ManyToManyField(blank=True, to='blog.recipeingredient', verbose_name='مواد لازم'),
        ),
    ]
