# Generated by Django 4.2.7 on 2024-11-16 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_remove_post_cover_image_alter_post_bookmarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='عکس کاور برای نمایش در لیست دستورها', null=True, upload_to='recipe_covers/%Y/%m/', verbose_name='عکس کاور'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='recipe_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='cook_time',
            field=models.PositiveIntegerField(default=60, verbose_name='زمان پخت (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='medium', max_length=10, verbose_name='سطح سختی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='recipe_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='prep_time',
            field=models.PositiveIntegerField(default=30, verbose_name='زمان آماده\u200cسازی (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='servings',
            field=models.PositiveIntegerField(default=4, verbose_name='تعداد نفرات'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='نامک'),
        ),
    ]
